#!/bin/sh
clear

VER="0.03"

#----------------------------------------------------------------#
# Name: dsfs-menu                                                #
#                                                                #
# Purpose: A simple to use (hopefully) prompting menu for the    #
#          dsfs dsadm command to help the average user find      #
#          and use these commands.                               #
#                                                                #
# Dependencies:  gum or less or more                             #
#                                                                #
# Author/Contributors (or whom to blame for this)                #
#   Lionel B. Dyck (lbdyck@gmail.com)                            #
#                                                                #
# Change History (top down):                                     #
#    2024/01/22 LBD - 0.03 add comment about more as an option   #
#                   -      improve colors and prompting          #
#    2024/01/22 LBD - 0.02 add comments and generalize pager     #
#    2024/01/08 LBD - 0.00 creation                              #
#                                                                #
#--------------------------------------------------------------=-#

#-------------------------------------------------------------=--#
# Comment and uncomment to define which pager to use for viewing #
#--------------------------------------------------------------=-#
# PAGER="gum pager"
# PAGER="more"
PAGER="less"

export TERM=xterm-256color

gum style \
        --foreground 226 --border-foreground 226 --border double \
        --align center --width 50 --margin "1 2" --padding "2 4" \
        'z/OS Open Tools dsfs User Menu' $VER

export GUM_INPUT_CURSOR_FOREGROUND="#200"
export GUM_INPUT_PROMPT_FOREGROUND="#200"
export GUM_IMPORT_PROMPT="* "

SEL=$(gum choose "createparm" "fileinfo" "fsinfo" "help" "query" "configquery" --header "Select DSFS Action:" --header.foreground="200")
case "$SEL" in
  createparm)
    echo "Selected" $SEL
    UID=$(id -u -n)
    HLQ=$(gum input --header=" HLQ to create - must be at least 2 qualifiers and the 1st must match your userid:" \
        --header.foreground="200" --placeholder="Enter HLQ")
    if [[ $HLQ != *.* ]]; then
       echo 'HLQ must have multiple qualifiers.'
       exit 0
    fi
    THLQ=$(echo "$HLQ" | tr '[:lower:]' '[:upper:]')
    if [[ ! "$THLQ" == "$UID"* ]]; then
       echo 'HLQ does NOT match your userid as it must - try again.'
       exit 0
    fi
    HLQ=$(echo $HLQ | tr '[:upper:]' '[:lower:]')
    TYPE=$(gum choose "txt" "bin" "rec" --header "Select DSFS type:" --header.foreground="200")
    DSORG=$(gum choose "PS" "PO" --header "Select dataset model type:" --header.foreground="200")

    if [ "$DSORG" = "PO" ]; then
       DSORG="dsorg(po) dsntype(liberary)"
       MODEL="-pdsmodel"
    elif [ "$DSORG" = "PS" ]; then
       DSORG="dsorg(ps)"
       MODEL="-psmodel"
    fi

    DATAC=$(gum input --width 8 --prompt "SMS Data Class:" --header.foreground="200")
    MGMTC=$(gum input --width 8 --prompt "SMS Management Class:" --header.foreground="200")
    STORC=$(gum input --width 8 --prompt "SMS Storage Class:" --header.foreground="200")

    if [ -n "$DATAC" ]; then
       DATAC="dataclas("$DATAC")"
       else
       DATAC=""
    fi

    if [ -n "$MGMTC" ]; then
       MGMTC="mgmtclas("$MGMTC")"
       else
       MGMTC=""
    fi

    if [ -n "$STORC" ]; then
       STORC="storclas("$STORC")"
       else
       STORC=""
    fi

    LRECL=$(gum input --header "Enter the LRECL for the model")
    BLKSZ=$(gum input --header "Enter the Blocksize for the model")
    RECFM=$(gum choose "FB" "VB" --header "Select Record Format:")

    SPACE=$(gum choose "cyl" "trk" --header.foreground="200" --header "Enter Allocation Type:")
    PRIM=$(gum input --header.foreground="200" --header "Enter Primary Space Quantity:")
    SEC=$(gum input  --header.foreground="200" --header "Enter Secondary Space Quantity:")

    CMD="dsadm createparm -path /dsfs/$TYPE/$UID $MODEL $DSORG recfm($RECFM) $LRECL $BLKSZ $SPACE space($PRIM,$SEC)"
    CMD="$CMD $DATAC $MGMTC $STORC"
echo "CreateParm is still experimental so does not really work yet"
    echo "cmd:" $CMD
    ;;
  fileinfo)
    HLQ=$(gum input --header "Enter HLQ to report on")
    TYPE=$(gum choose "txt" "bin" "rec" --header "Select DSFS type:" --header "Enter the dsfs type:")
    CMD="dsadm fileinfo -path /dsfs/$TYPE/$HLQ"
    ;;
  fsinfo)
    CMD="dsadm fsinfo"
    ;;
  help)
    HELP=$(gum choose "config" "configquery" "createparm" "fileinfo" "fsinfo" "query" --header "Select DSFS command:")
    CMD="dsadm help -topic $HELP"
    ;;
  query)
    QUERY=$(gum choose "compression" "dscache" "filecache" "iobydasd" "knpfs" "locking" "metacache" \
              "storage" "vnodecache" --no-limit --header "Select query options:")
    QUERY=$(echo $QUERY | sed 's/\b\(\w\)/ -\1/g')
    CMD="dsadm query $QUERY"
    ;;
  configquery)
    CMD="dsadm configquery -all"
    ;;
esac

$CMD | $PAGER

if [ -z "$SEL" ]; then
   echo 'No selection....'
fi

