#!/bin/sh
clear
VER="0.04"

#----------------------------------------------------------------#
# Name: mantastic                                                #
#                                                                #
# Purpose: Provide the shell user with an easy to use prompt     #
#          to find and display man pages.                        #
#                                                                #
# Dependencies:  gum or less or more                             #
#                                                                #
# Platforms:     Any shell where less or gum are installed       #
#                                                                #
# Author/Contributors (or whom to blame for this)                #
#   Lionel B. Dyck (lbdyck@gmail.com)                            #
#                                                                #
# Change History (top down):                                     #
#    2024/01/27 LBD - 0.04 Cleanup color and usage               #
#    2024/01/22 LBD - 0.03 add comment about more                #
#    2024/01/22 LBD - 0.02 add comments and generalize pager     #
#    2024/01/08 LBD - 0.00 creation                              #
#                                                                #
#--------------------------------------------------------------=-#

#-------------------------------------------------------------=--#
# Comment and uncomment to define which pager to use for viewing #
#--------------------------------------------------------------=-#
PAGER="gum pager"
# PAGER="more"
# PAGER="less"

export GUM_INPUT_CURSOR_FOREGROUND="#011"
export GUM_INPUT_PROMPT_FOREGROUND="#011"
export TERM=xterm-256color

gum style \
        --foreground 5 --border-foreground 5 --border double \
        --align center --width 50 --margin "1 2" --padding "2 4" \
        'z/OS Open Tools Man Viewer' $VER

if [ "$#" -eq 0 ]; then
    ARG=$(gum input --prompt "Enter a command for a manpage or a word to search for:" \
    --placeholder="e.g. ssh" --value=" ")
else
    ARG=$1
fi

MAN=$(gum choose $(man -k $ARG | cut -d" " -f1 | tail -n +2) \
  --header "Select Man Page to View" --header.foreground="11")
MAN=$(echo $MAN | cut -d" " -f1)

if [ -z "$MAN" ]; then
   echo 'No Selection.'
   else
      man $MAN | $PAGER
fi

