#!/bin/bash

VER='0.01'

#---------------------------------------------------#
# Name: zoauhelper                                  #
#                                                   #
# Purpose: Provide a helper for zoau commands       #
#                                                   #
# Dependencies: gum                                 #
#                                                   #
# Syntax:  zoauhelper                               #
#                                                   #
# Author/Contributors:                              #
#   Lionel B. Dyck (lbdyck@gmail.com)               #
#                                                   #
# Change History (current on top):                  #
#   2024/05/18 LBD - 0.01 Creation                  #
#---------------------------------------------------#
# Repository: github.com/lbdyck/prompters           #
#---------------------------------------------------#
# Copyleft by Lionel B. Dyck 2024                   #
#---------------------------------------------------#

#----------------------------------------------------------------#
# Define the color for the banner                                #
#  5 - purple                                                    #
# 12 - blue shade                                                #
# 33 - darker blue                                               #
# 46 - green                                                     #
# 51 - turq shade                                                #
#----------------------------------------------------------------#
COLOR=51

#----------------------------------------------------------------#
# Define export values that we need to look nice                 #
#----------------------------------------------------------------#

export GUM_INPUT_PROMPT_FOREGROUND="#$COLOR"
export GUM_INPUT_PLACEHOLDER=". . ."
export GUM_IMPORT_PROMPT="* "
export TERM=xterm-256color

clear

gum style \
   --foreground $COLOR --border-foreground $COLOR --border double \
   --align center --width 50 --margin "1 2" --padding "2 4" \
   'z/OS Automation Utilities (zoau) Helper' $VER

dir=$(dirname $(command -v dls)) 

zoau=$(ls $dir | \
    gum choose --header.foreground="$COLOR" \
    --height=18 \
    --header "Select zoau command for information")

if [ -z "$zoau" ]; then
   echo 'No selections made - exiting . . .'
   exit 0
fi

man $zoau | gum pager
