#!/bin/sh

VER='0.04'

#> This is work in progress any/all help appreciated

#---------------------------------------------------#
# Name: zotfile                                     #
#                                                   #
# Purpose: Simple filesystem viewer                 #
#                                                   #
# Dependencies: gum                                 #
#                                                   #
# Syntax:  zotfile directory                        #
#                                                   #
#          directory - where to start               #
#                      default=$HOME                #
#                                                   #
# Author/Contributors:                              #
#   Lionel B. Dyck (lbdyck@gmail.com)               #
#   Igor Todorovski                                 #
#                                                   #
# Change History (current on top):                  #
#   2024/02/14 LBD - 0.04 Improve messages          #
#   2024/02/13 LBD - 0.03 Allow starting location   #
#   2024/02/13 LBD - 0.02 Make it work (mostly)     #
#   2024/02/13 LBD - 0.01 Creation                  #
#---------------------------------------------------#
# Repository: github.com/lbdyck/prompters           #
#---------------------------------------------------#
# Copyleft by Lionel B. Dyck 2024                   #
#---------------------------------------------------#

#----------------------------------------------------------------#
# Define the color for the banner                                #
#  5 - purple                                                    #
# 12 - blue shade                                                #
# 33 - darker blue                                               #
# 46 - green                                                     #
# 51 - turq shade                                                #
#----------------------------------------------------------------#
COLOR=51

#----------------------------------------------------------------#
# Define export values that we need to look nice                 #
#----------------------------------------------------------------#

export GUM_INPUT_PROMPT_FOREGROUND="#$COLOR"
export GUM_INPUT_PLACEHOLDER=". . ."
export GUM_IMPORT_PROMPT="* "
export TERM=xterm-256color

#----------------------------------------------------------------#
# Define defaults                                                #
#----------------------------------------------------------------#
EDITOR="vim"
VIEWER="gum pager"

if [ -z "$1" ]; then
   DIR="$HOME"
 else
   DIR=$1
fi

doit()
{

banner

gum style \
   --foreground $COLOR --border-foreground $COLOR  \
   'Navigate left: go up dir, right select dir, enter select file or q to exit.' \
   'Scroll using up/down arrows.'

FP=$(gum file $DIR --height=20 --all --directory.foreground="$COLOR")
RC=$?

if [ "$RC" -eq 130 ] ; then
   echo "Escape entered - exiting. . . "
   exit 0
fi

DIR=$(dirname "$FP")
FILE=$(basename "$FP")

banner

OPT=$(gum choose 'Edit' 'View' --header.foreground="$COLOR" \
    --header="File $FP selected. Select file processing option or Escape to cancel.")
RC=$?

if [ "$RC" -eq 130 ] ; then
   doit
fi

case $OPT in
  Edit )
  cd $DIR
  $EDITOR $FILE
  doit
  ;;

  View )
  cd $DIR
  cat $FILE | $VIEWER
  doit
  ;;
esac
}

#----------------------#
# Display our banner   #
#----------------------#
banner ()
{
clear
gum style \
   --foreground $COLOR --border-foreground $COLOR --border double \
   --align center --width 50 --margin "1 2" --padding "1 2" \
   'z/OS Open Tools File Helper' $VER \
   " " \
   "Editor: $EDITOR" \
   "Viewer: $VIEWER"
}

##Start of the working code

#-------------------#
# Now actually DoIt #
#-------------------#

doit
